config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root :to=>"home#index"

  resources :notas
  resources :disciplinas
  resources :alunos

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
end

app/models/nota.rb
class Nota < ActiveRecord::Base
  belongs_to :aluno
  belongs_to :disciplina
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :endereco, :telefone, :renda)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]

  # GET /disciplinas
  # GET /disciplinas.json
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplina = Disciplina.new(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully created.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to @disciplina, notice: 'Disciplina was successfully updated.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to disciplinas_url, notice: 'Disciplina was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disciplina_params
      params.require(:disciplina).permit(:nome, :periodo)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notas_controller.rb
class NotasController < ApplicationController
  before_action :set_nota, only: [:show, :edit, :update, :destroy]

  # GET /notas
  # GET /notas.json
  def index
    @notas = Nota.all
  end

  # GET /notas/1
  # GET /notas/1.json
  def show
  end

  # GET /notas/new
  def new
    @nota = Nota.new
  end

  # GET /notas/1/edit
  def edit
  end

  # POST /notas
  # POST /notas.json
  def create
    @nota = Nota.new(nota_params)

    respond_to do |format|
      if @nota.save
        format.html { redirect_to @nota, notice: 'Nota was successfully created.' }
        format.json { render :show, status: :created, location: @nota }
      else
        format.html { render :new }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notas/1
  # PATCH/PUT /notas/1.json
  def update
    respond_to do |format|
      if @nota.update(nota_params)
        format.html { redirect_to @nota, notice: 'Nota was successfully updated.' }
        format.json { render :show, status: :ok, location: @nota }
      else
        format.html { render :edit }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notas/1
  # DELETE /notas/1.json
  def destroy
    @nota.destroy
    respond_to do |format|
      format.html { redirect_to notas_url, notice: 'Nota was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota
      @nota = Nota.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nota_params
      params.require(:nota).permit(:aluno_id, :disciplina_id, :p1, :p2, :p3)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notas_helper.rb
module NotasHelper
end

app/views/alunos/_form.html.erb
<%= simple_form_for(@aluno) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :endereco, label: 'Endereço' %>
    <%= f.input :telefone %>
    <%= f.input :renda %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form' %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Telefone</th>
      <th>Renda</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.endereco %></td>
        <td><%= aluno.telefone %></td>
        <td><%= aluno.renda %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Excluir', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form' %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @aluno.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @aluno.telefone %>
</p>

<p>
  <strong>Renda:</strong>
  <%= @aluno.renda %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/disciplinas/_form.html.erb
<%= simple_form_for(@disciplina) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.input :periodo %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/disciplinas/edit.html.erb
<h1>Editing Disciplina</h1>

<%= render 'form' %>

<%= link_to 'Show', @disciplina %> |
<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Disciplinas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Periodo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <td><%= disciplina.nome %></td>
        <td><%= disciplina.periodo %></td>
        <td><%= link_to 'Show', disciplina %></td>
        <td><%= link_to 'Edit', edit_disciplina_path(disciplina) %></td>
        <td><%= link_to 'Excluir', disciplina, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disciplina', new_disciplina_path %>

app/views/disciplinas/new.html.erb
<h1>New Disciplina</h1>

<%= render 'form' %>

<%= link_to 'Back', disciplinas_path %>

app/views/disciplinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @disciplina.nome %>
</p>

<p>
  <strong>Periodo:</strong>
  <%= @disciplina.periodo %>
</p>

<%= link_to 'Edit', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Back', disciplinas_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title>Academico</title>
		<meta name="keywords" content="" />
		<meta name="description" content="" />
  		<%= stylesheet_link_tag :all %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tag %>
	</head>

	<body>
		<div id="main">
			<div id="header">
				<div id="logo">
					<div id="logo_text">
						<!-- class="logo_colour", allows you to change the colour of the text -->
          				<h1><a href="index.html">Colégio<span class="logo_colour">Umbra</span></a></h1>
          				<h2>Referência em Ensino!</h2>
					</div>
				</div>

				<div id="menubar">
					<ul id="menu">
						<!-- put class="selected" in the li tag for the selected page - to highlight which page you're on -->
						<li><%= link_to 'Alunos', alunos_path %> </li>
				 		<li><%= link_to 'Disciplinas', disciplinas_path %> </li>
				 		<li><%= link_to 'Notas', notas_path %> </li>
					</ul>
				</div>
			</div>


			<div id="site_content">
				<div id="content">
					<!-- insert the page content here -->
					<!-- <h1>Cadastro</h1> -->
					<%= yield %>
				</div>
			</div>
		</div>

		<div id="content_footer"></div>
		<div id="footer">
      	Copyright &copy; 2015 | PLAYREPLAY
		</div>
	</body>

</html>

app/views/notas/_form.html.erb
<%= simple_form_for(@nota) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :aluno %>
    <%= f.association :disciplina %>
    <%= f.input :p1 %>
    <%= f.input :p2 %>
    <%= f.input :p3 %>
  </div>

  <div class="form-actions">
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/notas/edit.html.erb
<h1>Editing Nota</h1>

<%= render 'form' %>

<%= link_to 'Show', @nota %> |
<%= link_to 'Back', notas_path %>

app/views/notas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notas</h1>

<table>
  <thead>
    <tr>
      <th>Aluno</th>
      <th>Disciplina</th>
      <th>P1</th>
      <th>P2</th>
      <th>P3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notas.each do |nota| %>
      <tr>
        <td><%= nota.aluno.nome if nota.aluno %></td>
        <td><%= nota.disciplina.nome if nota.disciplina %></td>
        <td><%= nota.p1 %></td>
        <td><%= nota.p2 %></td>
        <td><%= nota.p3 %></td>
        <td><%= link_to 'Show', nota %></td>
        <td><%= link_to 'Edit', edit_nota_path(nota) %></td>
        <td><%= link_to 'Excluir', nota, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nota', new_nota_path %>

app/views/notas/new.html.erb
<h1>New Nota</h1>

<%= render 'form' %>

<%= link_to 'Back', notas_path %>

app/views/notas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aluno:</strong>
  <%= @nota.aluno %>
</p>

<p>
  <strong>Disciplina:</strong>
  <%= @nota.disciplina %>
</p>

<p>
  <strong>P1:</strong>
  <%= @nota.p1 %>
</p>

<p>
  <strong>P2:</strong>
  <%= @nota.p2 %>
</p>

<p>
  <strong>P3:</strong>
  <%= @nota.p3 %>
</p>

<%= link_to 'Edit', edit_nota_path(@nota) %> |
<%= link_to 'Back', notas_path %>